### ISSUE TITLE
Android Release build crash

### ISSUE THREAD

**Issue by ObelixSoftware** [Survicate/react-native-survicate#20]
When doing a release build we see a Null Pointer exception in SurveyPointFragment.java on line 28.

This works fine in debug mode.

Please advise

**Comment by AmirNexter** [comment]
@ObelixSoftware with what version? 1.1.6? #15

**Comment by kamilk-survicate** [comment]
@ObelixSoftware Are you using ProGuard for the Android release build? If so please use at least version 1.1.6 - the ProGuard configuration issue was fixed in version 1.1.6

**Comment by ObelixSoftware** [comment]
Yes was using ProGuard. Resolved by upgrading to 1.1.6. Thanks
