### ISSUE TITLE
In react native 0.68.2, the gradle sync fails again.

### ISSUE THREAD

**Issue by wenge8n** [Survicate/react-native-survicate#24]
In react native 0.68.2, the gradle sync fails again.

Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'compile' not found.

![image](https://user-images.githubusercontent.com/36442590/168644830-d01563d0-e6db-4234-95f0-b1cbb95a20b5.png)

How to resolve this?

_Originally posted by @wenge8n in https://github.com/Survicate/react-native-survicate/issues/15#issuecomment-1127912056_

**Comment by sergey-duzhych** [comment]
Hi @wenge8n , thank you for reporting this, I will let you know once there is any update from our developers on the above issue.

**Comment by wenge8n** [comment]
Ok thanks.

**Comment by sergey-duzhych** [comment]
Hi @wenge8n could you please provide us more details of your project configuration:

- package.json
- type of the project: metro / expo
- programming language: JavaScript / Typescript
- any changes applied in the gradle file of the project
- Any other relevant info 

You can also share this info at support@survicate.com or in the chat in your Survicate panel.

**Comment by wenge8n** [comment]
Hi @sergey-duzhych 
- "@survicate/react-native-survicate": "^1.1.9",
- metro
- javascript
- no changes

**Comment by wenge8n** [comment]
The issue is coming from here
https://github.com/gradle/gradle/issues/17051
As we are using gradle 7.04 in react native 0.68.2

**Comment by wenge8n** [comment]
The issue is coming from here
https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal
As we are using gradle 7.04 in react native 0.68.2

**Comment by robertcreaner** [comment]
Any update on this? Getting the same error

**Comment by wenge8n** [comment]
Here is temporary workaround. In the node_modules/@survicate/react-native-survicate/android/build.gradle

```diff
task androidJavadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += files(android.bootClasspath)
-    classpath += files(project.getConfigurations().getByName('compile').asList())
+    project.getConfigurations().getByName('implementation').setCanBeResolved(true)
+    classpath += files(project.getConfigurations().getByName('implementation').asList())
    include '**/*.java'
}
```

**Comment by sergey-duzhych** [comment]
Hi @wenge8n, version 1.1.11 that addresses the issue has been just released.
