### ISSUE TITLE
Could not find com.survicate:survicate-sdk:1.7.5

### ISSUE THREAD

**Issue by murilopf-up** [Survicate/react-native-survicate#40]
Hello everyone, I created a new RN project to test this lib and when I install the lib, if I try to run my app I get this error:

<img width="726" alt="Captura de Tela 2023-02-08 às 09 30 56" src="https://user-images.githubusercontent.com/109311014/217530349-18904d74-4fbc-4485-9174-1e0443a02e6c.png">

Versions: 
<img width="425" alt="Captura de Tela 2023-02-08 às 09 32 12" src="https://user-images.githubusercontent.com/109311014/217530652-782ee369-89dd-4efc-bfb4-aaf02cff3c3e.png">

I tried to finalize the steps before running again but the problem persists, Android only to iOS is fine.
can anyone help me with this problem?

**Comment by j-brzozowski** [comment]
Make sure that Survicate's maven repository is defined in `build.gradle` file. See 2nd step in "Configuration for Android" [here](https://developers.survicate.com/mobile-sdk/react-native/).

```
maven { url 'https://repo.survicate.com' }
```

**Comment by murilopf-up** [comment]
Hey, thanks for the quick response!
I found my error, my project didn't have an `allprojects` section in my `build.gradle` and I was putting the `maven { url 'https://repo.survicate.com' }` inside `repositories` and that it made an error.

So I created a section called `allprojects` and now it's working fine.

```
allprojects {
    repositories {
        // ...
        maven { url 'https://repo.survicate.com' }
    }
}
```
